// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Galv_ScreenButtons","status":true,"description":"(v.1.3) Show buttons on screen that can be touched or clicked.","parameters":{"Precache Buttons":"BtnUp,BtnDown,BtnRight,BtnLeft,BtnOk,BtnCancel,BtnEvent","Disable Mouse Move":"true","Button Fade":"30"}}
];
